import type { RoutineBlock, RoutineTemplate, Task, Zone } from "./types";

export const routineBlocks: RoutineBlock[] = [
  {
    id: "morning",
    name: "Morning",
    taskIds: [],
  },
  {
    id: "afternoon",
    name: "Afternoon",
    taskIds: [],
  },
  {
    id: "evening",
    name: "Evening",
    taskIds: [],
  },
];

export const zones: Zone[] = [
  {
    id: "kitchen",
    name: "Kitchen",
    description: "Keep the sink, counters, and visible floor easy to reset.",
    frequency: "daily",
    sortOrder: 1,
    active: true,
    suggestedTasks: [],
  },
  {
    id: "bathroom",
    name: "Bathroom",
    description: "A fast refresh for the sink, mirror, toilet, towels, and bin.",
    frequency: "daily",
    sortOrder: 2,
    active: true,
    suggestedTasks: [],
  },
  {
    id: "bedroom",
    name: "Bedroom and wardrobe",
    description: "Small resets that make the room feel calm before and after the day.",
    frequency: "daily",
    sortOrder: 3,
    active: true,
    suggestedTasks: [],
  },
  {
    id: "living",
    name: "Living room and desk",
    description: "The shared sitting and work surfaces that collect daily clutter.",
    frequency: "daily",
    sortOrder: 4,
    active: true,
    suggestedTasks: [],
  },
  {
    id: "entry",
    name: "Entrance",
    description: "Shoes, bags, mail, and parcels land here first—keep the path clear.",
    frequency: "daily",
    sortOrder: 5,
    active: true,
    suggestedTasks: [],
  },
];

export const tasks: Task[] = [
  // Kitchen — Manage layout:
  // "Today in this zone" = spotlightToday tasks (sink, counter, take out waste).
  // "Daily reset" = daily tasks without dailyPreviewOnly (sink, counter, floor,
  //   dishwasher, check waste). Take-out waste is dailyPreviewOnly → Today only.
  // Weekly / monthly / seasonal / as_needed match the section labels on Manage.

  // ─── Kitchen: Daily ───
  {
    id: "kitchen-daily-1",
    title: "Clear kitchen sink",
    zoneId: "kitchen",
    block: "morning",
    cadence: "daily",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 1,
    active: true,
    spotlightToday: true,
  },
  {
    id: "kitchen-daily-2",
    title: "Wipe counter",
    zoneId: "kitchen",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 3,
    required: true,
    sortOrder: 2,
    active: true,
    spotlightToday: true,
  },
  {
    id: "kitchen-daily-takeout",
    title: "Take out food waste",
    zoneId: "kitchen",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 2,
    required: true,
    sortOrder: 3,
    active: true,
    spotlightToday: true,
    dailyPreviewOnly: true,
  },
  {
    id: "kitchen-daily-3",
    title: "Reset visible floor",
    zoneId: "kitchen",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 4,
    required: true,
    sortOrder: 4,
    active: true,
  },
  {
    id: "kitchen-daily-4",
    title: "Load or unload dishwasher",
    zoneId: "kitchen",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 5,
    active: true,
  },
  {
    id: "kitchen-daily-5",
    title: "Check food waste",
    zoneId: "kitchen",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 2,
    required: true,
    sortOrder: 6,
    active: true,
  },
  // ─── Kitchen: Weekly ───
  {
    id: "kitchen-weekly-1",
    title: "Clean stovetop",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "kitchen-weekly-2",
    title: "Wipe cabinet fronts",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 8,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "kitchen-weekly-3",
    title: "Mop kitchen floor",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 12,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "kitchen-weekly-4",
    title: "Clear fridge leftovers",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 8,
    required: true,
    sortOrder: 4,
    active: true,
  },
  {
    id: "kitchen-weekly-5",
    title: "Restock basics",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 5,
    active: true,
  },
  // ─── Kitchen: Monthly ───
  {
    id: "kitchen-monthly-1",
    title: "Clean oven surface",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 15,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "kitchen-monthly-2",
    title: "Wipe inside fridge",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 15,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "kitchen-monthly-3",
    title: "Review pantry",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "kitchen-monthly-4",
    title: "Clean small appliances",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 12,
    required: true,
    sortOrder: 4,
    active: true,
  },
  // ─── Kitchen: Seasonal ───
  {
    id: "kitchen-seasonal-1",
    title: "Deep clean pantry",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 30,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "kitchen-seasonal-2",
    title: "Declutter mugs and containers",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 20,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "kitchen-seasonal-3",
    title: "Donate duplicate kitchen items",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 25,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "kitchen-seasonal-4",
    title: "Review holiday or hosting items",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 15,
    required: true,
    sortOrder: 4,
    active: true,
  },
  // ─── Kitchen: As needed ───
  {
    id: "kitchen-asneeded-1",
    title: "Descale kettle",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "as_needed",
    estimatedMinutes: 10,
    required: false,
    sortOrder: 1,
    active: true,
  },
  {
    id: "kitchen-asneeded-2",
    title: "Replace sponge",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "as_needed",
    estimatedMinutes: 2,
    required: false,
    sortOrder: 2,
    active: true,
  },
  {
    id: "kitchen-asneeded-3",
    title: "Fix loose drawer handle",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "as_needed",
    estimatedMinutes: 15,
    required: false,
    sortOrder: 3,
    active: true,
  },
  // Bathroom — Manage layout:
  // Intentionally no Bathroom dailies or daily reset rows. Weekly / monthly /
  //   seasonal / as_needed match Manage section labels.

  // ─── Bathroom: Weekly ───
  {
    id: "bathroom-weekly-1",
    title: "Clean shower screen",
    zoneId: "bathroom",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "bathroom-weekly-2",
    title: "Clean toilet",
    zoneId: "bathroom",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "bathroom-weekly-3",
    title: "Replace towels",
    zoneId: "bathroom",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "bathroom-weekly-4",
    title: "Empty bathroom bin",
    zoneId: "bathroom",
    block: "evening",
    cadence: "weekly",
    estimatedMinutes: 3,
    required: true,
    sortOrder: 4,
    active: true,
  },
  {
    id: "bathroom-weekly-5",
    title: "Put laundry in hamper",
    zoneId: "bathroom",
    block: "evening",
    cadence: "weekly",
    estimatedMinutes: 2,
    required: true,
    sortOrder: 5,
    active: true,
  },
  // ─── Bathroom: Monthly ───
  {
    id: "bathroom-monthly-1",
    title: "Mop bathroom floor",
    zoneId: "bathroom",
    block: "evening",
    cadence: "monthly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "bathroom-monthly-2",
    title: "Refill products",
    zoneId: "bathroom",
    block: "evening",
    cadence: "monthly",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "bathroom-monthly-3",
    title: "Wipe mirror",
    zoneId: "bathroom",
    block: "evening",
    cadence: "monthly",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "bathroom-monthly-4",
    title: "Wipe bathroom counter",
    zoneId: "bathroom",
    block: "evening",
    cadence: "monthly",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 4,
    active: true,
  },
  // ─── Bathroom: Seasonal ───
  {
    id: "bathroom-seasonal-1",
    title: "Deep clean shower grout",
    zoneId: "bathroom",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 45,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "bathroom-seasonal-2",
    title: "Declutter beauty and skincare products",
    zoneId: "bathroom",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 30,
    required: true,
    sortOrder: 2,
    active: true,
  },
  // ─── Bathroom: As needed ───
  {
    id: "bathroom-asneeded-1",
    title: "Replace toothbrush",
    zoneId: "bathroom",
    block: "afternoon",
    cadence: "as_needed",
    estimatedMinutes: 3,
    required: false,
    sortOrder: 1,
    active: true,
  },
  {
    id: "bathroom-asneeded-2",
    title: "Descale showerhead",
    zoneId: "bathroom",
    block: "afternoon",
    cadence: "as_needed",
    estimatedMinutes: 20,
    required: false,
    sortOrder: 2,
    active: true,
  },
  {
    id: "bathroom-asneeded-3",
    title: "Refill soap",
    zoneId: "bathroom",
    block: "afternoon",
    cadence: "as_needed",
    estimatedMinutes: 2,
    required: false,
    sortOrder: 3,
    active: true,
  },
  {
    id: "bathroom-asneeded-4",
    title: "Rinse shower area",
    zoneId: "bathroom",
    block: "afternoon",
    cadence: "as_needed",
    estimatedMinutes: 3,
    required: false,
    sortOrder: 4,
    active: true,
  },
  {
    id: "bathroom-asneeded-5",
    title: "Wash bath mat",
    zoneId: "bathroom",
    block: "evening",
    cadence: "as_needed",
    estimatedMinutes: 20,
    required: false,
    sortOrder: 5,
    active: true,
  },
  {
    id: "bathroom-asneeded-6",
    title: "Clean drain",
    zoneId: "bathroom",
    block: "evening",
    cadence: "as_needed",
    estimatedMinutes: 10,
    required: false,
    sortOrder: 6,
    active: true,
  },

  // Bedroom — Manage layout:
  // Same rules as Kitchen: "Today in this zone" = spotlightToday tasks;
  // "Daily reset" = daily tasks without dailyPreviewOnly. One dailyPreviewOnly
  //   row stays Today-only preview. Weekly / monthly / seasonal / as_needed
  //   match Manage section labels.

  // ─── Bedroom: Daily ───
  {
    id: "bedroom-daily-1",
    title: "Make bed",
    zoneId: "bedroom",
    block: "morning",
    cadence: "daily",
    estimatedMinutes: 2,
    required: true,
    sortOrder: 1,
    active: true,
    spotlightToday: true,
  },
  {
    id: "bedroom-daily-2",
    title: "Open curtains or blinds",
    zoneId: "bedroom",
    block: "morning",
    cadence: "daily",
    estimatedMinutes: 1,
    required: true,
    sortOrder: 2,
    active: true,
    spotlightToday: true,
  },
  {
    id: "bedroom-daily-takeout",
    title: "Put worn clothes aside",
    zoneId: "bedroom",
    block: "morning",
    cadence: "daily",
    estimatedMinutes: 1,
    required: true,
    sortOrder: 3,
    active: true,
    spotlightToday: true,
    dailyPreviewOnly: true,
  },
  {
    id: "bedroom-daily-3",
    title: "Set out tomorrow's clothes",
    zoneId: "bedroom",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 3,
    required: true,
    sortOrder: 4,
    active: true,
  },
  {
    id: "bedroom-daily-4",
    title: "Clear clothing pile",
    zoneId: "bedroom",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 5,
    active: true,
  },
  // ─── Bedroom: Weekly ───
  {
    id: "bedroom-weekly-1",
    title: "Change bedsheets",
    zoneId: "bedroom",
    block: "morning",
    cadence: "weekly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "bedroom-weekly-2",
    title: "Change pillows",
    zoneId: "bedroom",
    block: "morning",
    cadence: "weekly",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "bedroom-weekly-3",
    title: "Vacuum bedroom floor",
    zoneId: "bedroom",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "bedroom-weekly-4",
    title: "Reset items",
    zoneId: "bedroom",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 4,
    active: true,
  },
  // ─── Bedroom: Monthly ───
  {
    id: "bedroom-monthly-1",
    title: "Review clothes pile",
    zoneId: "bedroom",
    block: "morning",
    cadence: "monthly",
    estimatedMinutes: 15,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "bedroom-monthly-2",
    title: "Wipe bedside tables and surfaces",
    zoneId: "bedroom",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "bedroom-monthly-3",
    title: "Review shoes and bags",
    zoneId: "bedroom",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 20,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "bedroom-monthly-4",
    title: "Tidy bedside drawers",
    zoneId: "bedroom",
    block: "evening",
    cadence: "monthly",
    estimatedMinutes: 15,
    required: true,
    sortOrder: 4,
    active: true,
  },
  // ─── Bedroom: Seasonal ───
  {
    id: "bedroom-seasonal-1",
    title: "Review clothes for fit and comfort",
    zoneId: "bedroom",
    block: "evening",
    cadence: "seasonal",
    estimatedMinutes: 30,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "bedroom-seasonal-2",
    title: "Store off-season clothing",
    zoneId: "bedroom",
    block: "evening",
    cadence: "seasonal",
    estimatedMinutes: 30,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "bedroom-seasonal-3",
    title: "Declutter drawers",
    zoneId: "bedroom",
    block: "evening",
    cadence: "seasonal",
    estimatedMinutes: 30,
    required: true,
    sortOrder: 3,
    active: true,
  },
  // ─── Bedroom: As needed ───
  {
    id: "bedroom-asneeded-1",
    title: "Hem pants",
    zoneId: "bedroom",
    block: "morning",
    cadence: "as_needed",
    estimatedMinutes: 60,
    required: false,
    sortOrder: 1,
    active: true,
  },
  {
    id: "bedroom-asneeded-2",
    title: "Repair loose button",
    zoneId: "bedroom",
    block: "morning",
    cadence: "as_needed",
    estimatedMinutes: 10,
    required: false,
    sortOrder: 2,
    active: true,
  },
  {
    id: "bedroom-asneeded-3",
    title: "List item for resale",
    zoneId: "bedroom",
    block: "afternoon",
    cadence: "as_needed",
    estimatedMinutes: 15,
    required: false,
    sortOrder: 3,
    active: true,
  },
  {
    id: "bedroom-asneeded-4",
    title: "Pack donation bag",
    zoneId: "bedroom",
    block: "afternoon",
    cadence: "as_needed",
    estimatedMinutes: 10,
    required: false,
    sortOrder: 4,
    active: true,
  },
  {
    id: "bedroom-asneeded-5",
    title: "Clean mirror",
    zoneId: "bedroom",
    block: "afternoon",
    cadence: "as_needed",
    estimatedMinutes: 5,
    required: false,
    sortOrder: 5,
    active: true,
  },

  // ─── Living room: Daily ───
  {
    id: "living-daily-1",
    title: "Quick desk reset",
    zoneId: "living",
    block: "morning",
    cadence: "daily",
    estimatedMinutes: 3,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "living-daily-2",
    title: "Clear coffee table",
    zoneId: "living",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 3,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "living-daily-3",
    title: "Reset cushions and throws",
    zoneId: "living",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 2,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "living-daily-4",
    title: "Put away stray items",
    zoneId: "living",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 4,
    active: true,
  },
  // ─── Living room: Weekly ───
  {
    id: "living-weekly-1",
    title: "Vacuum living area",
    zoneId: "living",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "living-weekly-2",
    title: "Dust shelves and surfaces",
    zoneId: "living",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 8,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "living-weekly-3",
    title: "Wipe TV and electronics",
    zoneId: "living",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "living-weekly-4",
    title: "Tidy bookshelves",
    zoneId: "living",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 4,
    active: true,
  },
  // ─── Living room: Monthly ───
  {
    id: "living-monthly-1",
    title: "Clean windows inside",
    zoneId: "living",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 15,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "living-monthly-2",
    title: "Wipe skirting boards",
    zoneId: "living",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "living-monthly-3",
    title: "Clean light fixtures",
    zoneId: "living",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "living-monthly-4",
    title: "Reorganise desk drawers",
    zoneId: "living",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 4,
    active: true,
  },
  // ─── Living room: Seasonal ───
  {
    id: "living-seasonal-1",
    title: "Deep clean sofa and upholstery",
    zoneId: "living",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 30,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "living-seasonal-2",
    title: "Wash curtains or blinds",
    zoneId: "living",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 15,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "living-seasonal-3",
    title: "Deep clean carpet",
    zoneId: "living",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 25,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "living-seasonal-4",
    title: "Declutter shelves and storage",
    zoneId: "living",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 20,
    required: true,
    sortOrder: 4,
    active: true,
  },
  // ─── Entry: Weekly ───
  {
    id: "entry-weekly-1",
    title: "Sort loose mail",
    zoneId: "entry",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 3,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "entry-weekly-2",
    title: "Clear entry bench",
    zoneId: "entry",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "entry-weekly-3",
    title: "Sort returns and errands",
    zoneId: "entry",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "entry-weekly-4",
    title: "Sweep entry floor",
    zoneId: "entry",
    block: "evening",
    cadence: "weekly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 4,
    active: true,
  },
  {
    id: "entry-weekly-5",
    title: "Clear shoes from walkway",
    zoneId: "entry",
    block: "evening",
    cadence: "weekly",
    estimatedMinutes: 1,
    required: true,
    sortOrder: 5,
    active: true,
  },
  {
    id: "entry-weekly-6",
    title: "Hang bags and coats",
    zoneId: "entry",
    block: "evening",
    cadence: "weekly",
    estimatedMinutes: 2,
    required: true,
    sortOrder: 6,
    active: true,
  },
  // ─── Entry: Monthly ───
  {
    id: "entry-monthly-1",
    title: "Reset entry storage",
    zoneId: "entry",
    block: "evening",
    cadence: "monthly",
    estimatedMinutes: 25,
    required: true,
    sortOrder: 1,
    active: true,
  },
  // ─── Entry: Seasonal ───
  {
    id: "entry-seasonal-1",
    title: "Set up wet-weather entry",
    zoneId: "entry",
    block: "morning",
    cadence: "seasonal",
    estimatedMinutes: 30,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "entry-seasonal-2",
    title: "Create donation bag for shoes, coats, and bags",
    zoneId: "entry",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 30,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "entry-seasonal-3",
    title: "Review seasonal entry items",
    zoneId: "entry",
    block: "evening",
    cadence: "seasonal",
    estimatedMinutes: 20,
    required: true,
    sortOrder: 3,
    active: true,
  },
  // ─── Entry: As needed ───
  {
    id: "entry-asneeded-1",
    title: "Clean muddy shoes",
    zoneId: "entry",
    block: "morning",
    cadence: "as_needed",
    estimatedMinutes: 10,
    required: false,
    sortOrder: 1,
    active: true,
  },
  {
    id: "entry-asneeded-2",
    title: "Prepare items to return",
    zoneId: "entry",
    block: "morning",
    cadence: "as_needed",
    estimatedMinutes: 10,
    required: false,
    sortOrder: 2,
    active: true,
  },
  {
    id: "entry-asneeded-3",
    title: "Handle parcel return",
    zoneId: "entry",
    block: "afternoon",
    cadence: "as_needed",
    estimatedMinutes: 10,
    required: false,
    sortOrder: 3,
    active: true,
  },
  {
    id: "entry-asneeded-4",
    title: "Wash entry mat",
    zoneId: "entry",
    block: "evening",
    cadence: "as_needed",
    estimatedMinutes: 20,
    required: false,
    sortOrder: 4,
    active: true,
  },
  {
    id: "entry-asneeded-5",
    title: "Reset after guests",
    zoneId: "entry",
    block: "evening",
    cadence: "as_needed",
    estimatedMinutes: 10,
    required: false,
    sortOrder: 5,
    active: true,
  },

];

export const templates: RoutineTemplate[] = [
  {
    id: "one-bedroom-reset",
    name: "One-Bedroom Reset",
    description: "The default balanced plan for a bedroom, bathroom, kitchen, living area, and entry.",
    apartmentType: "one-bedroom",
    taskIds: tasks.map((t) => t.id),
    highlights: ["Balanced daily blocks", "All apartment zones", "Gentle evening close"],
  },
  {
    id: "studio-reset",
    name: "Studio Reset",
    description: "A compact routine for one-room living where surfaces and sink resets matter most.",
    apartmentType: "studio",
    taskIds: tasks
      .filter((t) => t.zoneId === "kitchen" || t.zoneId === "bathroom" || t.zoneId === "living")
      .map((t) => t.id),
    highlights: ["Small-space flow", "Visible surfaces", "Kitchen reset"],
  },
  {
    id: "shared-apartment-reset",
    name: "Shared Apartment Reset",
    description: "A routine that keeps personal areas tidy and gives shared spaces a fast daily reset.",
    apartmentType: "shared",
    taskIds: tasks.map((t) => t.id),
    highlights: ["Shared surfaces", "Personal reset", "Low-friction chores"],
  },
];

export const defaultTemplateId = "one-bedroom-reset";
export const defaultZoneId = "kitchen";
export const defaultResetTime = "01:00";
