import type { RoutineBlock, RoutineTemplate, Task, Zone } from "./types";

export const routineBlocks: RoutineBlock[] = [
  {
    id: "morning",
    name: "Morning",
    taskIds: [],
  },
  {
    id: "afternoon",
    name: "Afternoon",
    taskIds: [],
  },
  {
    id: "evening",
    name: "Evening",
    taskIds: [],
  },
];

export const zones: Zone[] = [
  {
    id: "kitchen",
    name: "Kitchen",
    description: "Keep the sink, counters, and visible floor easy to reset.",
    frequency: "daily",
    sortOrder: 1,
    active: true,
    suggestedTasks: [],
  },
  {
    id: "bathroom",
    name: "Bathroom",
    description: "A fast refresh for the sink, mirror, toilet, towels, and bin.",
    frequency: "daily",
    sortOrder: 2,
    active: true,
    suggestedTasks: [],
  },
  {
    id: "bedroom",
    name: "Bedroom and wardrobe",
    description: "Small resets that make the room feel calm before and after the day.",
    frequency: "daily",
    sortOrder: 3,
    active: true,
    suggestedTasks: [],
  },
  {
    id: "living",
    name: "Living room and desk",
    description: "The shared sitting and work surfaces that collect daily clutter.",
    frequency: "daily",
    sortOrder: 4,
    active: true,
    suggestedTasks: [],
  },
  {
    id: "entry",
    name: "Entry and drop zones",
    description: "The first visible landing spots for shoes, bags, mail, and laundry.",
    frequency: "daily",
    sortOrder: 5,
    active: true,
    suggestedTasks: [],
  },
];

export const tasks: Task[] = [
  // ─── Kitchen: Daily ───
  {
    id: "kitchen-daily-1",
    title: "Clear kitchen sink",
    zoneId: "kitchen",
    block: "morning",
    cadence: "daily",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "kitchen-daily-2",
    title: "Wipe counter",
    zoneId: "kitchen",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 3,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "kitchen-daily-3",
    title: "Reset visible floor",
    zoneId: "kitchen",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 4,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "kitchen-daily-4",
    title: "Load or unload dishwasher",
    zoneId: "kitchen",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 4,
    active: true,
  },
  {
    id: "kitchen-daily-5",
    title: "Check food waste",
    zoneId: "kitchen",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 2,
    required: true,
    sortOrder: 5,
    active: true,
  },
  // ─── Kitchen: Weekly ───
  {
    id: "kitchen-weekly-1",
    title: "Clean stovetop",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "kitchen-weekly-2",
    title: "Wipe cabinet fronts",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 8,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "kitchen-weekly-3",
    title: "Mop kitchen floor",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 12,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "kitchen-weekly-4",
    title: "Clear fridge leftovers",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 8,
    required: true,
    sortOrder: 4,
    active: true,
  },
  {
    id: "kitchen-weekly-5",
    title: "Restock basics",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 5,
    active: true,
  },
  // ─── Kitchen: Monthly ───
  {
    id: "kitchen-monthly-1",
    title: "Clean oven surface",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 15,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "kitchen-monthly-2",
    title: "Wipe inside fridge",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 15,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "kitchen-monthly-3",
    title: "Review pantry",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "kitchen-monthly-4",
    title: "Clean small appliances",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 12,
    required: true,
    sortOrder: 4,
    active: true,
  },
  // ─── Kitchen: Seasonal ───
  {
    id: "kitchen-seasonal-1",
    title: "Deep clean pantry",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 30,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "kitchen-seasonal-2",
    title: "Declutter condiments and freezer",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 20,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "kitchen-seasonal-3",
    title: "Descale kettle",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "kitchen-seasonal-4",
    title: "Replace sponge",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 2,
    required: true,
    sortOrder: 4,
    active: true,
  },
  {
    id: "kitchen-seasonal-5",
    title: "Fix loose drawer handle",
    zoneId: "kitchen",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 15,
    required: true,
    sortOrder: 5,
    active: true,
  },
  // ─── Bathroom: Daily ───
  {
    id: "bathroom-daily-1",
    title: "Wipe sink and mirror",
    zoneId: "bathroom",
    block: "morning",
    cadence: "daily",
    estimatedMinutes: 3,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "bathroom-daily-2",
    title: "Hang up towels",
    zoneId: "bathroom",
    block: "morning",
    cadence: "daily",
    estimatedMinutes: 1,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "bathroom-daily-3",
    title: "Quick toilet wipe",
    zoneId: "bathroom",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 3,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "bathroom-daily-4",
    title: "Clear counter clutter",
    zoneId: "bathroom",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 2,
    required: true,
    sortOrder: 4,
    active: true,
  },
  // ─── Bathroom: Weekly ───
  {
    id: "bathroom-weekly-1",
    title: "Scrub shower or tub",
    zoneId: "bathroom",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 12,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "bathroom-weekly-2",
    title: "Clean toilet thoroughly",
    zoneId: "bathroom",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 8,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "bathroom-weekly-3",
    title: "Mop bathroom floor",
    zoneId: "bathroom",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 8,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "bathroom-weekly-4",
    title: "Replace hand towels",
    zoneId: "bathroom",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 3,
    required: true,
    sortOrder: 4,
    active: true,
  },
  {
    id: "bathroom-weekly-5",
    title: "Empty bathroom bin",
    zoneId: "bathroom",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 2,
    required: true,
    sortOrder: 5,
    active: true,
  },
  // ─── Bathroom: Monthly ───
  {
    id: "bathroom-monthly-1",
    title: "Descale showerhead",
    zoneId: "bathroom",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "bathroom-monthly-2",
    title: "Clean grout and tiles",
    zoneId: "bathroom",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 20,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "bathroom-monthly-3",
    title: "Organise under-sink cabinet",
    zoneId: "bathroom",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "bathroom-monthly-4",
    title: "Check product expiry dates",
    zoneId: "bathroom",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 4,
    active: true,
  },
  // ─── Bathroom: Seasonal ───
  {
    id: "bathroom-seasonal-1",
    title: "Deep clean extractor fan",
    zoneId: "bathroom",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 20,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "bathroom-seasonal-2",
    title: "Reseal bath or shower",
    zoneId: "bathroom",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 30,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "bathroom-seasonal-3",
    title: "Replace shower curtain or liner",
    zoneId: "bathroom",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "bathroom-seasonal-4",
    title: "Declutter medicine cabinet",
    zoneId: "bathroom",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 15,
    required: true,
    sortOrder: 4,
    active: true,
  },
  // ─── Bedroom: Daily ───
  {
    id: "bedroom-daily-1",
    title: "Make bed",
    zoneId: "bedroom",
    block: "morning",
    cadence: "daily",
    estimatedMinutes: 2,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "bedroom-daily-2",
    title: "Open curtains",
    zoneId: "bedroom",
    block: "morning",
    cadence: "daily",
    estimatedMinutes: 1,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "bedroom-daily-3",
    title: "Clear bedside table",
    zoneId: "bedroom",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 2,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "bedroom-daily-4",
    title: "Put away clothes",
    zoneId: "bedroom",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 4,
    active: true,
  },
  // ─── Bedroom: Weekly ───
  {
    id: "bedroom-weekly-1",
    title: "Change bed sheets",
    zoneId: "bedroom",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "bedroom-weekly-2",
    title: "Vacuum bedroom floor",
    zoneId: "bedroom",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 8,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "bedroom-weekly-3",
    title: "Dust surfaces and shelves",
    zoneId: "bedroom",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 8,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "bedroom-weekly-4",
    title: "Sort laundry basket",
    zoneId: "bedroom",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 4,
    active: true,
  },
  // ─── Bedroom: Monthly ───
  {
    id: "bedroom-monthly-1",
    title: "Rotate mattress",
    zoneId: "bedroom",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "bedroom-monthly-2",
    title: "Clean under bed",
    zoneId: "bedroom",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "bedroom-monthly-3",
    title: "Organise wardrobe section",
    zoneId: "bedroom",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 15,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "bedroom-monthly-4",
    title: "Wipe wardrobe doors",
    zoneId: "bedroom",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 4,
    active: true,
  },
  // ─── Bedroom: Seasonal ───
  {
    id: "bedroom-seasonal-1",
    title: "Swap seasonal wardrobe",
    zoneId: "bedroom",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 30,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "bedroom-seasonal-2",
    title: "Deep clean carpet or rug",
    zoneId: "bedroom",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 20,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "bedroom-seasonal-3",
    title: "Wash curtains or blinds",
    zoneId: "bedroom",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 15,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "bedroom-seasonal-4",
    title: "Donate unused clothes",
    zoneId: "bedroom",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 20,
    required: true,
    sortOrder: 4,
    active: true,
  },
  // ─── Living room: Daily ───
  {
    id: "living-daily-1",
    title: "Quick desk reset",
    zoneId: "living",
    block: "morning",
    cadence: "daily",
    estimatedMinutes: 3,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "living-daily-2",
    title: "Clear coffee table",
    zoneId: "living",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 3,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "living-daily-3",
    title: "Reset cushions and throws",
    zoneId: "living",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 2,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "living-daily-4",
    title: "Put away stray items",
    zoneId: "living",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 4,
    active: true,
  },
  // ─── Living room: Weekly ───
  {
    id: "living-weekly-1",
    title: "Vacuum living area",
    zoneId: "living",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "living-weekly-2",
    title: "Dust shelves and surfaces",
    zoneId: "living",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 8,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "living-weekly-3",
    title: "Wipe TV and electronics",
    zoneId: "living",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "living-weekly-4",
    title: "Tidy bookshelves",
    zoneId: "living",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 4,
    active: true,
  },
  // ─── Living room: Monthly ───
  {
    id: "living-monthly-1",
    title: "Clean windows inside",
    zoneId: "living",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 15,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "living-monthly-2",
    title: "Wipe skirting boards",
    zoneId: "living",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "living-monthly-3",
    title: "Clean light fixtures",
    zoneId: "living",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "living-monthly-4",
    title: "Reorganise desk drawers",
    zoneId: "living",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 4,
    active: true,
  },
  // ─── Living room: Seasonal ───
  {
    id: "living-seasonal-1",
    title: "Deep clean sofa and upholstery",
    zoneId: "living",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 30,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "living-seasonal-2",
    title: "Wash curtains or blinds",
    zoneId: "living",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 15,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "living-seasonal-3",
    title: "Deep clean carpet",
    zoneId: "living",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 25,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "living-seasonal-4",
    title: "Declutter shelves and storage",
    zoneId: "living",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 20,
    required: true,
    sortOrder: 4,
    active: true,
  },
  // ─── Entry: Daily ───
  {
    id: "entry-daily-1",
    title: "Put away shoes and bags",
    zoneId: "entry",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 3,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "entry-daily-2",
    title: "Sort or recycle mail",
    zoneId: "entry",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 2,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "entry-daily-3",
    title: "Clear entry surface",
    zoneId: "entry",
    block: "evening",
    cadence: "daily",
    estimatedMinutes: 2,
    required: true,
    sortOrder: 3,
    active: true,
  },
  // ─── Entry: Weekly ───
  {
    id: "entry-weekly-1",
    title: "Sweep or vacuum entry",
    zoneId: "entry",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "entry-weekly-2",
    title: "Wipe door handles",
    zoneId: "entry",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 3,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "entry-weekly-3",
    title: "Take out rubbish and recycling",
    zoneId: "entry",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "entry-weekly-4",
    title: "Wipe shoe rack or mat",
    zoneId: "entry",
    block: "afternoon",
    cadence: "weekly",
    estimatedMinutes: 3,
    required: true,
    sortOrder: 4,
    active: true,
  },
  // ─── Entry: Monthly ───
  {
    id: "entry-monthly-1",
    title: "Clean front door",
    zoneId: "entry",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 8,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "entry-monthly-2",
    title: "Declutter coat hooks",
    zoneId: "entry",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "entry-monthly-3",
    title: "Wash door mat",
    zoneId: "entry",
    block: "afternoon",
    cadence: "monthly",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 3,
    active: true,
  },
  // ─── Entry: Seasonal ───
  {
    id: "entry-seasonal-1",
    title: "Deep clean hallway floor",
    zoneId: "entry",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 15,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "entry-seasonal-2",
    title: "Sort seasonal shoes and coats",
    zoneId: "entry",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 20,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "entry-seasonal-3",
    title: "Check smoke detector batteries",
    zoneId: "entry",
    block: "afternoon",
    cadence: "seasonal",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 3,
    active: true,
  },
];

export const templates: RoutineTemplate[] = [
  {
    id: "one-bedroom-reset",
    name: "One-Bedroom Reset",
    description: "The default balanced plan for a bedroom, bathroom, kitchen, living area, and entry.",
    apartmentType: "one-bedroom",
    taskIds: tasks.map((t) => t.id),
    highlights: ["Balanced daily blocks", "All apartment zones", "Gentle evening close"],
  },
  {
    id: "studio-reset",
    name: "Studio Reset",
    description: "A compact routine for one-room living where surfaces and sink resets matter most.",
    apartmentType: "studio",
    taskIds: tasks
      .filter((t) => t.zoneId === "kitchen" || t.zoneId === "bathroom" || t.zoneId === "living")
      .map((t) => t.id),
    highlights: ["Small-space flow", "Visible surfaces", "Kitchen reset"],
  },
  {
    id: "shared-apartment-reset",
    name: "Shared Apartment Reset",
    description: "A routine that keeps personal areas tidy and gives shared spaces a fast daily reset.",
    apartmentType: "shared",
    taskIds: tasks.map((t) => t.id),
    highlights: ["Shared surfaces", "Personal reset", "Low-friction chores"],
  },
];

export const defaultTemplateId = "one-bedroom-reset";
export const defaultZoneId = "kitchen";
export const defaultResetTime = "01:00";
