import type { RoutineBlock, RoutineTemplate, Task, Zone } from "./types";

export const routineBlocks: RoutineBlock[] = [
  {
    id: "morning",
    name: "Morning",
    taskIds: [
      "make-bed",
      "open-curtains",
      "bathroom-sink-wipe",
      "clear-kitchen-sink-morning",
      "check-zone",
      "quick-desk-reset",
    ],
  },
  {
    id: "afternoon",
    name: "Afternoon",
    taskIds: [
      "zone-task",
      "clear-hotspot",
      "put-away-ten",
      "wipe-visible-surface",
      "visible-floor",
      "shared-surface-reset",
    ],
  },
  {
    id: "evening",
    name: "Evening",
    taskIds: [
      "clear-kitchen-sink-evening",
      "wipe-kitchen-counter",
      "reset-living-room",
      "put-away-laundry",
      "setup-tomorrow",
      "take-out-small-rubbish",
    ],
  },
];

export const zones: Zone[] = [
  {
    id: "entry",
    name: "Entry and drop zones",
    description: "The first visible landing spots for shoes, bags, mail, and laundry.",
    frequency: "daily",
    sortOrder: 1,
    active: true,
    suggestedTasks: [
      "Put away shoes and bags",
      "Clear the entry surface",
      "Sort or recycle mail",
      "Empty a small rubbish bin",
      "Reset the visible laundry corner",
    ],
  },
  {
    id: "kitchen",
    name: "Kitchen",
    description: "Keep the sink, counters, and visible floor easy to reset.",
    frequency: "daily",
    sortOrder: 2,
    active: true,
    suggestedTasks: [
      "Clear the sink",
      "Wipe counters",
      "Clean one fridge shelf",
      "Wipe the microwave",
      "Sweep the visible floor",
    ],
  },
  {
    id: "bathroom",
    name: "Bathroom",
    description: "A fast refresh for the sink, mirror, toilet, towels, and bin.",
    frequency: "daily",
    sortOrder: 3,
    active: true,
    suggestedTasks: [
      "Wipe the sink",
      "Clean the mirror",
      "Do a quick toilet clean",
      "Empty the bin",
      "Replace towels",
    ],
  },
  {
    id: "bedroom",
    name: "Bedroom and wardrobe",
    description: "Small resets that make the room feel calm before and after the day.",
    frequency: "daily",
    sortOrder: 4,
    active: true,
    suggestedTasks: [
      "Make the bed",
      "Clear the bedside table",
      "Put clothes away",
      "Reset laundry",
      "Vacuum the visible floor",
    ],
  },
  {
    id: "living",
    name: "Living room and desk",
    description: "The shared sitting and work surfaces that collect daily clutter.",
    frequency: "daily",
    sortOrder: 5,
    active: true,
    suggestedTasks: [
      "Clear the coffee table",
      "Reset cushions",
      "Dust visible surfaces",
      "Clear the desk",
      "Put away stray items",
    ],
  },
];

export const tasks: Task[] = [
  {
    id: "make-bed",
    title: "Make bed",
    zoneId: "bedroom",
    block: "morning",
    estimatedMinutes: 2,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "open-curtains",
    title: "Open curtains and reset bedroom surface",
    zoneId: "bedroom",
    block: "morning",
    estimatedMinutes: 2,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "bathroom-sink-wipe",
    title: "Bathroom sink wipe",
    zoneId: "bathroom",
    block: "morning",
    estimatedMinutes: 3,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "clear-kitchen-sink-morning",
    title: "Clear kitchen sink",
    zoneId: "kitchen",
    block: "morning",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 4,
    active: true,
  },
  {
    id: "check-zone",
    title: "Check today's zone",
    block: "morning",
    estimatedMinutes: 1,
    required: true,
    sortOrder: 5,
    active: true,
  },
  {
    id: "quick-desk-reset",
    title: "Quick desk reset",
    zoneId: "living",
    block: "morning",
    estimatedMinutes: 3,
    required: true,
    sortOrder: 6,
    active: true,
  },
  {
    id: "zone-task",
    title: "Start 15-minute zone task",
    block: "afternoon",
    estimatedMinutes: 15,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "clear-hotspot",
    title: "Clear one hotspot",
    block: "afternoon",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "put-away-ten",
    title: "Put away 10 items",
    block: "afternoon",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "wipe-visible-surface",
    title: "Wipe one visible surface",
    block: "afternoon",
    estimatedMinutes: 3,
    required: true,
    sortOrder: 4,
    active: true,
  },
  {
    id: "visible-floor",
    title: "Sweep or vacuum one visible area",
    block: "afternoon",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 5,
    active: true,
  },
  {
    id: "shared-surface-reset",
    title: "Reset one shared surface",
    zoneId: "living",
    block: "afternoon",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 6,
    active: true,
  },
  {
    id: "clear-kitchen-sink-evening",
    title: "Clear kitchen sink",
    zoneId: "kitchen",
    block: "evening",
    estimatedMinutes: 10,
    required: true,
    sortOrder: 1,
    active: true,
  },
  {
    id: "wipe-kitchen-counter",
    title: "Wipe kitchen counter",
    zoneId: "kitchen",
    block: "evening",
    estimatedMinutes: 3,
    required: true,
    sortOrder: 2,
    active: true,
  },
  {
    id: "reset-living-room",
    title: "Reset living room",
    zoneId: "living",
    block: "evening",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 3,
    active: true,
  },
  {
    id: "put-away-laundry",
    title: "Put away clothes or laundry",
    zoneId: "bedroom",
    block: "evening",
    estimatedMinutes: 5,
    required: true,
    sortOrder: 4,
    active: true,
  },
  {
    id: "setup-tomorrow",
    title: "Set up tomorrow's first cleaning task",
    block: "evening",
    estimatedMinutes: 2,
    required: true,
    sortOrder: 5,
    active: true,
  },
  {
    id: "take-out-small-rubbish",
    title: "Take out small rubbish",
    zoneId: "entry",
    block: "evening",
    estimatedMinutes: 4,
    required: true,
    sortOrder: 6,
    active: true,
  },
];

export const templates: RoutineTemplate[] = [
  {
    id: "studio-reset",
    name: "Studio Reset",
    description: "A compact routine for one-room living where surfaces and sink resets matter most.",
    apartmentType: "studio",
    taskIds: [
      "make-bed",
      "open-curtains",
      "bathroom-sink-wipe",
      "clear-kitchen-sink-morning",
      "check-zone",
      "zone-task",
      "clear-hotspot",
      "put-away-ten",
      "wipe-visible-surface",
      "visible-floor",
      "clear-kitchen-sink-evening",
      "wipe-kitchen-counter",
      "reset-living-room",
      "put-away-laundry",
      "setup-tomorrow",
    ],
    highlights: ["Small-space flow", "Visible surfaces", "Kitchen reset"],
  },
  {
    id: "one-bedroom-reset",
    name: "One-Bedroom Reset",
    description: "The default balanced plan for a bedroom, bathroom, kitchen, living area, and entry.",
    apartmentType: "one-bedroom",
    taskIds: tasks.map((task) => task.id),
    highlights: ["Balanced daily blocks", "All apartment zones", "Gentle evening close"],
  },
  {
    id: "shared-apartment-reset",
    name: "Shared Apartment Reset",
    description: "A routine that keeps personal areas tidy and gives shared spaces a fast daily reset.",
    apartmentType: "shared",
    taskIds: [
      "make-bed",
      "open-curtains",
      "bathroom-sink-wipe",
      "clear-kitchen-sink-morning",
      "quick-desk-reset",
      "zone-task",
      "clear-hotspot",
      "put-away-ten",
      "wipe-visible-surface",
      "shared-surface-reset",
      "clear-kitchen-sink-evening",
      "wipe-kitchen-counter",
      "reset-living-room",
      "put-away-laundry",
      "take-out-small-rubbish",
      "setup-tomorrow",
    ],
    highlights: ["Shared surfaces", "Personal reset", "Low-friction chores"],
  },
];

export const defaultTemplateId = "one-bedroom-reset";
export const defaultZoneId = "kitchen";
export const defaultResetTime = "03:00";
